name: Deploy Web-Client
on:
  push:
    branches:
      - main
    paths:
      - "packages/web-client/**"
      - ".github/workflows/wc-deploy.yml"
      - ".github/workflows/wc-setup/action.yml"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  web-client-deploy-dapp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "true"
          token: ${{ secrets.SUBMODULE_PAT }}
      - name: Set-up env
        uses: ./.github/workflows/wc-setup
      - run: npm run wc:build:static
      - run: |
          set -euxo pipefail
          DFX_VERSION=0.13.1 sh -ci "$(curl -fsSL https://smartcontracts.org/install.sh)"
      - run: dfx identity list
      - run: |
          touch actions_identity.pem
          echo "${{ secrets.CANISTER_CONTROLLER_SECRET_KEY }}" > actions_identity.pem
          dfx identity import --disable-encryption actions actions_identity.pem
          rm actions_identity.pem
          dfx identity use actions
      - run: dfx deploy webclient --network ic --no-wallet

  web-client-deploy-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "true"
          token: ${{ secrets.SUBMODULE_PAT }}
      - name: Set-up env
        uses: ./.github/workflows/wc-setup
      - run: npm run wc:build

      - name: Deploy production build
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CLOUDFLARE_WORKERS_DEPLOY_API_TOKEN }}
          workingDirectory: "packages/web-client/"
          command: pages publish ".svelte-kit/cloudflare" --branch=main --project-name=hot-or-not-web-client --commit-dirty=true
        env:
          CLOUDFLARE_ACCOUNT_ID: "a209c523d2d9646cc56227dbe6ce3ede"
